name: Test Build
on:
  push:
    paths:
      - ".github/workflows/*"
      - "**/*.js"
      - "**/*.ts"
      - "**/*.vue"
      - "public/**/*"
      - "package-lock.json"
      - "package.json"
  pull_request:
    paths:
      - "**/*.js"
      - "**/*.ts"
      - "**/*.vue"
      - "public/**/*"
      - "package-lock.json"
      - "package.json"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build: [ legacy ]
        include:
          - build: legacy
            BUILD_ARGS: ""
            BUILD_EXTENSION: true
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "17"

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build ${{ matrix.BUILD_ARGS }}

      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.build }}
          path: ./dist

      - name: Build Extension
        if: ${{ matrix.BUILD_EXTENSION }}
        run: npm run make-extension

      - name: Publish artifact - Extension
        if: ${{ matrix.BUILD_EXTENSION }}
        uses: actions/upload-artifact@v2
        with:
          name: extension
          path: ./dist
