name: Build Release

on:
  push:
  release:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install Dependencies
        run: npm ci

      - name: Build Legacy
        env:
          GZIP: "--best"
        run: |
          npm run build
          tar -czf legacy.tar.gz -C ./dist .
          cd dist
          zip -rJ9 ../legacy.zip *
          cd ..

      - name: Build Extension (on legacy)
        env:
          GZIP: "--best"
        run: |
          npm run make-extension
          cd dist
          zip -rJ9 ../extension.zip *
          cd ..

      - name: Checksum
        run: sha256sum *.tar.gz *.zip > sha256sum.txt

      - name: Upload files to GitHub release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ./*.zip*
          tag: ${{ github.ref }}
